config/routes.rb
Rails.application.routes.draw do
  
  root to: "application#home"
  resources :pods
  resources :books
  devise_for :users, :controllers => { registrations: 'registrations', omniauth_callbacks: 'omniauth'}

  resources :pods, only: [:show] do
    resources :books, only: [:new, :show, :edit, :update, :destroy]
  end
  
  
  #pod_books GET /pod/pod_id/book/:id 
  

  

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    has_many :book_pods
    has_many :pods, through: :book_pods
    belongs_to :category, optional: true
end

app/models/book_pod.rb
class BookPod < ApplicationRecord
    belongs_to :book 
    belongs_to :pod
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :books
    has_many :pods
end

app/models/pod.rb
class Pod < ApplicationRecord
    has_many :book_pods
    has_many :books, through: :book_pods
    has_many :user_pods
    has_many :users, through: :user_pods
    belongs_to :category, optional: true

    accepts_nested_attributes_for :books, reject_if: proc { |attr| attr['title'].blank?  }

    #if time write a custom writer
    #def book_attributes=(book_attributes)
    #    binding.pry
    #    @book = self.books.build(book_attributes)
    #    @book.save
    #end

    #def books_attributes=(books_attributes)
    #    books_attributes.values.each do |books_attribute|
    #        book = Book.find_or_create_by(books_attribute)
    #      self.books << books
    #    end
    #  end

end

app/models/user.rb
class User < ApplicationRecord
  
  has_many :user_pods
  has_many :pods, through: :user_pods

  accepts_nested_attributes_for :pods

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :omniauthable, omniauth_providers:[:facebook, :google_oauth2]
  

  def self.create_from_provider_data(provider_data)
    where(provider: provider_data.provider, uid: provider_data.uid).first_or_create do |user|
      user.email = provider_data.info.email
      user.password = Devise.friendly_token[0, 20]
    end
  end
end

app/models/user_pod.rb
class UserPod < ApplicationRecord

    belongs_to :user 
    belongs_to :pod
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def home
        @pods = Pod.all
        @categories = Category.all
        @user = User.pods.all
    end
    
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

    def index
        @books = Book.all
    end

    def new
        @book = Book.new
    end

    def create
        @book = Book.new(book_params)
        binding.pry
        if @book.save
            redirect_to pod_path
        else
            render "new"
        end
    end

    def show
        if !@book
            redirect_to pods_path
        end
    end

    def edit
        if !@book
            redirect_to pods_path
        end
    end

    def update
        if @book
            @book.update(book_params)
            if @book.errors.any?
                render "edit"
            else
                redirect_to pods_path
            end
        else
            render "edit"
        end
    end

    def destroy
        @book.destroy
        redirect_to pods_path
    end
    


  private

  def set_book
    @book = Book.find_by_id(params[:id])
  end

  def book_params
    params.require(:book).permit(:title, :author, :author_bio, :book_summary)
  end

end

app/controllers/omniauth_controller.rb
class OmniauthController < ApplicationController

    def facebook
        @user = User.create_from_provider_data(request.env['omniauth.auth'])
        if @user.persisted?
            sign_in_and_redirect @user
        else
            flash[:error] = "Facebook sign-in unsuccessful. Please try again"
            redirect_to new_user_registration_path
        end
    end

    def google_oauth2
        @user = User.create_from_provider_data(request.env['omniauth.auth'])
        if @user.persisted?
            sign_in_and_redirect @user
        else
            flash[:error] = "Google sign-in unsuccessful. Please try again"
            redirect_to new_user_registration_path
        end
    end

    def failure
        flash[:error] = "Sign in unsucessful. Please try again"
        redirect_to new_user_registration_path
    end
end

app/controllers/pods_controller.rb
class PodsController < ApplicationController

    before_action :set_pod, only: [:show, :edit, :update, :destroy]

    def index
        @pods = Pod.all
    end

    def new
        @pod = current_user.pods.build
        @pod.books.build
    end

    def create
        @pod = current_user.pods.build(pod_params)
        if @pod.save
            @pod.books.build
            current_user.pods << @pod
            redirect_to pod_path(@pod)#There is something wrong here. Where should this take the user - you need to think more - Maybe this should go to the newly created pod show page
        else
            redirect_to pods_path
        end
    end

    def show
        if !@pod
            redirect_to pods_path
        end
    end

    def edit
        if !@pod
            redirect_to pods_path
        end
    end

    def update
        if @pod
            @pod.update(pod_params)
            if @pod.errors.any?
                render "edit"
            else
                redirect_to pods_path
            end
        else
            render "edit"
        end
    end

    def destroy
        @pod.destroy
        redirect_to pod_path
    end

    private

    def pod_params
        params.require(:pod).permit(:pod_name, :current_book, category_id:[], books_attributes:[:title, :author, :author_bio, :book_summary])
    end

    def set_pod
        @pod = Pod.find_by_id(params[:id])
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

    private
        def sign_up_params
            params.require(:user).permit(:email, :password, :password_confirmation, :name, :professional_field, :bio)
        end
    
        def account_update_params
            params.require(:user).permit(:email, :password, :password_confirmation, :current_password, :name, :professional_field, :bio)
        end
end

    

app/helpers/application_helper.rb
module ApplicationHelper  
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/omniauth_helper.rb
module OmniauthHelper
end

app/helpers/pods_helper.rb
module PodsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/application/home.erb
<h1>Hi, <%= current_user.name %>! Welcome to the Reading Pod</h1>

<!-- if there is a current user show below else do not-->
<!-- if user_signed_in? else sign in or sign up above-->

<% if user_signed_in? %> 
  <h3>Reading Pods</h3>

  <li><%= link_to "View Your Profile", edit_user_registration_path %></li>
  <br>
  <li><%= link_to "View Reading Pods", pods_path %></li>
  <br>
  <br>
  <li><%= link_to "View Current Months Books", books_path %></li><!--TODO: custom scope method  for this -->
  <br>
  <br>
  <%= button_to "Create Reading Pod", new_pod_path, method: "get" %>
  <br>
  <br>
  <%= form_with model: @category do |f| %>
    <%= f.collection_select :category_id, Category.all, :id, :name, prompt: "Categories" %>
    <%= f.submit %>
  <% end %>
<% else %>
  <h3>Please sign in or sign up above</h3>
<% end %>

<%#= form_with model: @pod do |f| %>
  <%#= f.collection_select :pod_id, Pod.all, :id, :name, prompt: "Select Reading Pod" %>
  <%#= f.submit %>
<%# end %>

app/views/layouts/_message.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_nav.erb
<div class="nav_bar">   
    <% if user_signed_in? %>        
    <nav>
        <ul>
        <% if current_user.provider == "" %>
            <li><%= link_to "Edit Your Profile", edit_user_registration_path(current_user) %></li>
        <% end %>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
    <% else %>
            <li><%= link_to "Sign In", new_user_session_path %></li>
            <li><%= link_to "Sign Up", new_user_registration_path %></li>
        </ul>
    </nav>
    <% end %>         
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReadingPod</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <header>
    <%= render "layouts/nav" %>
    <%= render "layouts/message" %>
  </header>
  <body>
    
    <%= yield %>
  </body>
</html>

app/views/pods/edit.erb
<% if @pod.errors.any? %>
    <h4 class="error"><%= @pod.errors.full_messages.to_sentence %></h4>
<% end %>

<%= form_with model: @pod, local: true do | f | %> 
    <%= f.label :name %>
    <%= f.text_field :name, class: @pod.errors.any? ? "error-field" : nil %><br><br>
    <%= f.fields_for :book do |b| %>
        <%= b.label "Book of the Month" %>
        <%= b.text_field :current_book %><br><br>
        <%= b.label "Book Author" %>
        <%= b.text_field :author %><br><br>
        <%= b.label "Author Bio" %>
        <%= b.text_area :author_bio %><br><br>
        <%= b.label "Book Summary" %>
        <%= b.text_area :book_summary %><br><br>
    <% end %>
    <%= f.submit "Create Pod" %>
<% end %>

app/views/pods/index.erb
<h3>Reading Pods</h3>

<ul>
<% @pods.each do | pod | %>
        <li> <%= link_to(pod.pod_name, pod) %></li>
<% end %>
</ul>

app/views/pods/new.erb
<% if @pod.errors.any? %>
    <h4 class="error"><%= @pod.errors.full_messages.to_sentence %></h4>
<% end %>

<%= form_with model: @pod, local: true do | f | %> 
    <%= f.label :pod_name %>
    <%= f.text_field :pod_name, class: @pod.errors.any? ? "error-field" : nil %><br><br>
    <%= f.fields_for :books do |b| %>
        <%= b.label "Book of the Month" %>
        <%= b.text_field :title %><br><br>
        <%= b.label "Book Author" %>
        <%= b.text_field :author %><br><br>
        <%= b.label "Author Bio" %>
        <%= b.text_area :author_bio %><br><br>
        <%= b.label "Book Summary" %>
        <%= b.text_area :book_summary %><br><br>
    <% end %>
    <%= f.collection_select :category_id, Category.all, :id, :name %><br><br>
    <%= f.submit "Create Pod" %>
<% end %>
<!-- Parameters:
{"authenticity_token"=>"qT2liBrM4efGFFxQFAipJVMI5dFJaN1OfdvQEx1o9PxvDh9qkJA01NyVk4kxSBZ70iukg1+m67vEbYp9+1BE5w==",
 "pod"=>{"pod_name"=>"The Imposters", "book"=>{"title"=>"The only way is up", "author"=>"yaz", "author_bio"=>"up, uppity, up", "book_summary"=>"uplifting"}, "category_id"=>"8"},
 "commit"=>"Create Pod"} -->

 <!-- from here, when I hit create, it takes me to the pods show page and lists the pods name but none of the book attributes??>

app/views/pods/show.erb
<h2>Here is your newly created Reading Pod</h2><br><br>

<%= @pod.pod_name %><br><br>
<% @pod.books.each do | attr | %>
    <li><%= attr.title %></li><br><br>
    <li><%= attr.author %></li><br><br>
    <li><%= attr.author_bio %></li><br><br>
    <li><%= attr.book_summary %></li><br><br>
<% end %>
<br>
<br>
<br>
<br>

<%= button_to "Join Reading Pod", new_pod_path %>
<%= button_to "Create Reading Pod", new_pod_path %>

<!-- If current_user joins then Join this pod should add this pod to the users pod listing
- It should indicate that status has changed and the user is now a member of this pod
- It should display a message welcoming the user to the pod Else do nothing -->

<!-- 
STRETCH GOALS - links to purchase the book (physical & audio). Weekly prods. I think I need to assign an overall admin who can edit and update the pods

< button_to "Join Reading Pod", ??? would this update action, method: "patch" %>

Ternary operator 
- 
- STRETCH GOAL - It should start a countdown to the book read finishing time.-->

app/views/users/edit.erb
<h3>Hello, <%= current_user ? current_user.name : nil %>! Edit your Profile</h3>

app/views/users/show.erb
<h3>Hello, <%= current_user ? current_user.name : nil %>! Welcome to your profile page</h3>
<li><%= link_to("Delete Your Account", @user, method: :delete, data:{confirm: "We miss you already, reconsider?"}) %></li>
<li><%= link_to "View Your Profile", user_path %></li>
<li><%= link_to "View Your Profile", user_path %></li>